export const COUNTRY_CODES = [
  { code: '+91', name: 'India', label: 'IN (+91)' },
  { code: '+1', name: 'United States', label: 'US (+1)' },
  { code: '+44', name: 'United Kingdom', label: 'UK (+44)' },
  { code: '+61', name: 'Australia', label: 'AU (+61)' },
  { code: '+93', name: 'Afghanistan', label: 'AF (+93)' },
  { code: '+355', name: 'Albania', label: 'AL (+355)' },
  { code: '+213', name: 'Algeria', label: 'DZ (+213)' },
  { code: '+376', name: 'Andorra', label: 'AD (+376)' },
  { code: '+244', name: 'Angola', label: 'AO (+244)' },
  { code: '+54', name: 'Argentina', label: 'AR (+54)' },
  { code: '+374', name: 'Armenia', label: 'AM (+374)' },
  { code: '+43', name: 'Austria', label: 'AT (+43)' },
  { code: '+994', name: 'Azerbaijan', label: 'AZ (+994)' },
  { code: '+973', name: 'Bahrain', label: 'BH (+973)' },
  { code: '+880', name: 'Bangladesh', label: 'BD (+880)' },
  { code: '+375', name: 'Belarus', label: 'BY (+375)' },
  { code: '+32', name: 'Belgium', label: 'BE (+32)' },
  { code: '+501', name: 'Belize', label: 'BZ (+501)' },
  { code: '+229', name: 'Benin', label: 'BJ (+229)' },
  { code: '+975', name: 'Bhutan', label: 'BT (+975)' },
  { code: '+591', name: 'Bolivia', label: 'BO (+591)' },
  { code: '+387', name: 'Bosnia', label: 'BA (+387)' },
  { code: '+267', name: 'Botswana', label: 'BW (+267)' },
  { code: '+55', name: 'Brazil', label: 'BR (+55)' },
  { code: '+359', name: 'Bulgaria', label: 'BG (+359)' },
  { code: '+226', name: 'Burkina Faso', label: 'BF (+226)' },
  { code: '+257', name: 'Burundi', label: 'BI (+257)' },
  { code: '+855', name: 'Cambodia', label: 'KH (+855)' },
  { code: '+237', name: 'Cameroon', label: 'CM (+237)' },
  { code: '+1', name: 'Canada', label: 'CA (+1)' },
  { code: '+238', name: 'Cape Verde', label: 'CV (+238)' },
  { code: '+236', name: 'Central African Republic', label: 'CF (+236)' },
  { code: '+235', name: 'Chad', label: 'TD (+235)' },
  { code: '+56', name: 'Chile', label: 'CL (+56)' },
  { code: '+86', name: 'China', label: 'CN (+86)' },
  { code: '+57', name: 'Colombia', label: 'CO (+57)' },
  { code: '+269', name: 'Comoros', label: 'KM (+269)' },
  { code: '+242', name: 'Congo', label: 'CG (+242)' },
  { code: '+506', name: 'Costa Rica', label: 'CR (+506)' },
  { code: '+385', name: 'Croatia', label: 'HR (+385)' },
  { code: '+53', name: 'Cuba', label: 'CU (+53)' },
  { code: '+357', name: 'Cyprus', label: 'CY (+357)' },
  { code: '+420', name: 'Czech Republic', label: 'CZ (+420)' },
  { code: '+45', name: 'Denmark', label: 'DK (+45)' },
  { code: '+253', name: 'Djibouti', label: 'DJ (+253)' },
  { code: '+1', name: 'Dominican Republic', label: 'DO (+1)' },
  { code: '+593', name: 'Ecuador', label: 'EC (+593)' },
  { code: '+20', name: 'Egypt', label: 'EG (+20)' },
  { code: '+503', name: 'El Salvador', label: 'SV (+503)' },
  { code: '+240', name: 'Equatorial Guinea', label: 'GQ (+240)' },
  { code: '+291', name: 'Eritrea', label: 'ER (+291)' },
  { code: '+372', name: 'Estonia', label: 'EE (+372)' },
  { code: '+251', name: 'Ethiopia', label: 'ET (+251)' },
  { code: '+679', name: 'Fiji', label: 'FJ (+679)' },
  { code: '+358', name: 'Finland', label: 'FI (+358)' },
  { code: '+33', name: 'France', label: 'FR (+33)' },
  { code: '+241', name: 'Gabon', label: 'GA (+241)' },
  { code: '+220', name: 'Gambia', label: 'GM (+220)' },
  { code: '+995', name: 'Georgia', label: 'GE (+995)' },
  { code: '+49', name: 'Germany', label: 'DE (+49)' },
  { code: '+233', name: 'Ghana', label: 'GH (+233)' },
  { code: '+30', name: 'Greece', label: 'GR (+30)' },
  { code: '+502', name: 'Guatemala', label: 'GT (+502)' },
  { code: '+224', name: 'Guinea', label: 'GN (+224)' },
  { code: '+592', name: 'Guyana', label: 'GY (+592)' },
  { code: '+509', name: 'Haiti', label: 'HT (+509)' },
  { code: '+504', name: 'Honduras', label: 'HN (+504)' },
  { code: '+36', name: 'Hungary', label: 'HU (+36)' },
  { code: '+354', name: 'Iceland', label: 'IS (+354)' },
  { code: '+62', name: 'Indonesia', label: 'ID (+62)' },
  { code: '+98', name: 'Iran', label: 'IR (+98)' },
  { code: '+964', name: 'Iraq', label: 'IQ (+964)' },
  { code: '+353', name: 'Ireland', label: 'IE (+353)' },
  { code: '+972', name: 'Israel', label: 'IL (+972)' },
  { code: '+39', name: 'Italy', label: 'IT (+39)' },
  { code: '+1', name: 'Jamaica', label: 'JM (+1)' },
  { code: '+81', name: 'Japan', label: 'JP (+81)' },
  { code: '+962', name: 'Jordan', label: 'JO (+962)' },
  { code: '+7', name: 'Kazakhstan', label: 'KZ (+7)' },
  { code: '+254', name: 'Kenya', label: 'KE (+254)' },
  { code: '+850', name: 'North Korea', label: 'KP (+850)' },
  { code: '+82', name: 'South Korea', label: 'KR (+82)' },
  { code: '+965', name: 'Kuwait', label: 'KW (+965)' },
  { code: '+996', name: 'Kyrgyzstan', label: 'KG (+996)' },
  { code: '+856', name: 'Laos', label: 'LA (+856)' },
  { code: '+371', name: 'Latvia', label: 'LV (+371)' },
  { code: '+961', name: 'Lebanon', label: 'LB (+961)' },
  { code: '+266', name: 'Lesotho', label: 'LS (+266)' },
  { code: '+231', name: 'Liberia', label: 'LR (+231)' },
  { code: '+218', name: 'Libya', label: 'LY (+218)' },
  { code: '+423', name: 'Liechtenstein', label: 'LI (+423)' },
  { code: '+370', name: 'Lithuania', label: 'LT (+370)' },
  { code: '+352', name: 'Luxembourg', label: 'LU (+352)' },
  { code: '+261', name: 'Madagascar', label: 'MG (+261)' },
  { code: '+265', name: 'Malawi', label: 'MW (+265)' },
  { code: '+60', name: 'Malaysia', label: 'MY (+60)' },
  { code: '+960', name: 'Maldives', label: 'MV (+960)' },
  { code: '+223', name: 'Mali', label: 'ML (+223)' },
  { code: '+356', name: 'Malta', label: 'MT (+356)' },
  { code: '+222', name: 'Mauritania', label: 'MR (+222)' },
  { code: '+230', name: 'Mauritius', label: 'MU (+230)' },
  { code: '+52', name: 'Mexico', label: 'MX (+52)' },
  { code: '+373', name: 'Moldova', label: 'MD (+373)' },
  { code: '+377', name: 'Monaco', label: 'MC (+377)' },
  { code: '+976', name: 'Mongolia', label: 'MN (+976)' },
  { code: '+382', name: 'Montenegro', label: 'ME (+382)' },
  { code: '+212', name: 'Morocco', label: 'MA (+212)' },
  { code: '+258', name: 'Mozambique', label: 'MZ (+258)' },
  { code: '+95', name: 'Myanmar', label: 'MM (+95)' },
  { code: '+264', name: 'Namibia', label: 'NA (+264)' },
  { code: '+977', name: 'Nepal', label: 'NP (+977)' },
  { code: '+31', name: 'Netherlands', label: 'NL (+31)' },
  { code: '+64', name: 'New Zealand', label: 'NZ (+64)' },
  { code: '+505', name: 'Nicaragua', label: 'NI (+505)' },
  { code: '+227', name: 'Niger', label: 'NE (+227)' },
  { code: '+234', name: 'Nigeria', label: 'NG (+234)' },
  { code: '+47', name: 'Norway', label: 'NO (+47)' },
  { code: '+968', name: 'Oman', label: 'OM (+968)' },
  { code: '+92', name: 'Pakistan', label: 'PK (+92)' },
  { code: '+970', name: 'Palestine', label: 'PS (+970)' },
  { code: '+507', name: 'Panama', label: 'PA (+507)' },
  { code: '+675', name: 'Papua New Guinea', label: 'PG (+675)' },
  { code: '+595', name: 'Paraguay', label: 'PY (+595)' },
  { code: '+51', name: 'Peru', label: 'PE (+51)' },
  { code: '+63', name: 'Philippines', label: 'PH (+63)' },
  { code: '+48', name: 'Poland', label: 'PL (+48)' },
  { code: '+351', name: 'Portugal', label: 'PT (+351)' },
  { code: '+974', name: 'Qatar', label: 'QA (+974)' },
  { code: '+40', name: 'Romania', label: 'RO (+40)' },
  { code: '+7', name: 'Russia', label: 'RU (+7)' },
  { code: '+250', name: 'Rwanda', label: 'RW (+250)' },
  { code: '+966', name: 'Saudi Arabia', label: 'SA (+966)' },
  { code: '+221', name: 'Senegal', label: 'SN (+221)' },
  { code: '+381', name: 'Serbia', label: 'RS (+381)' },
  { code: '+248', name: 'Seychelles', label: 'SC (+248)' },
  { code: '+232', name: 'Sierra Leone', label: 'SL (+232)' },
  { code: '+65', name: 'Singapore', label: 'SG (+65)' },
  { code: '+421', name: 'Slovakia', label: 'SK (+421)' },
  { code: '+386', name: 'Slovenia', label: 'SI (+386)' },
  { code: '+252', name: 'Somalia', label: 'SO (+252)' },
  { code: '+27', name: 'South Africa', label: 'ZA (+27)' },
  { code: '+34', name: 'Spain', label: 'ES (+34)' },
  { code: '+94', name: 'Sri Lanka', label: 'LK (+94)' },
  { code: '+249', name: 'Sudan', label: 'SD (+249)' },
  { code: '+46', name: 'Sweden', label: 'SE (+46)' },
  { code: '+41', name: 'Switzerland', label: 'CH (+41)' },
  { code: '+963', name: 'Syria', label: 'SY (+963)' },
  { code: '+886', name: 'Taiwan', label: 'TW (+886)' },
  { code: '+992', name: 'Tajikistan', label: 'TJ (+992)' },
  { code: '+255', name: 'Tanzania', label: 'TZ (+255)' },
  { code: '+66', name: 'Thailand', label: 'TH (+66)' },
  { code: '+228', name: 'Togo', label: 'TG (+228)' },
  { code: '+216', name: 'Tunisia', label: 'TN (+216)' },
  { code: '+90', name: 'Turkey', label: 'TR (+90)' },
  { code: '+993', name: 'Turkmenistan', label: 'TM (+993)' },
  { code: '+256', name: 'Uganda', label: 'UG (+256)' },
  { code: '+380', name: 'Ukraine', label: 'UA (+380)' },
  { code: '+971', name: 'United Arab Emirates', label: 'AE (+971)' },
  { code: '+598', name: 'Uruguay', label: 'UY (+598)' },
  { code: '+998', name: 'Uzbekistan', label: 'UZ (+998)' },
  { code: '+58', name: 'Venezuela', label: 'VE (+58)' },
  { code: '+84', name: 'Vietnam', label: 'VN (+84)' },
  { code: '+967', name: 'Yemen', label: 'YE (+967)' },
  { code: '+260', name: 'Zambia', label: 'ZM (+260)' },
  { code: '+263', name: 'Zimbabwe', label: 'ZW (+263)' }
];
